server:
  port: 8081
  servlet:
    context-path: /flyshare
# 日志配置
logging:
  config: classpath:log4j2.xml
  level:
    com.kakasys.flyshare: debug

spring:
  # 全局jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  # 模板引擎配置
  freemarker:
    cache: false
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    settings:
      template_update_delay: 0
    template-loader-path: classpath:/templates/ftl
    check-template-location: true
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/flyshare?useUnicode=true&characterEncoding=utf8
    #username: root
    #password: 123456
    url: jdbc:mysql://106.13.61.81:3306/flyshare?useUnicode=true&characterEncoding=utf8
    username: wuxiaohai
    password: wxh19900624
    #schema: classpath:create-table.sql
    #data: classpath:init-data.sql
    #initialization-mode: never

# mybatis 配置
mybatis:
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml