server:
  port: 8081
  servlet:
    context-path: /flyshare
# 日志配置
logging:
  config: classpath:log4j2-dev.xml
  level:
    com.kakasys.flyshare: debug

spring:
  # 全局jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.61.81:3306/flyshare?useUnicode=true&characterEncoding=utf8
    username: wuxiaohai
    password: wxh19900624
    hikari:
      auto-commit: true
      connection-timeout: 10000 # 等待来自池的连接的最大毫秒数  10秒
      idle-timeout: 300000 # 连接允许在池中闲置的最长时间 5分钟
      maxLifetime: 600000 # 池中连接最长生命周期 10分钟
      minimumIdle: 5 # 池中维护的最小空闲连接数
      maximumPoolSize: 10 #池中最大连接数，包括闲置和使用中的连接

# mybatis 配置
mybatis:
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml